### ISSUE TITLE
[Speaker Right ] 音声が再生されない

### ISSUE THREAD

**Issue by Maplejavas** [niwaniwa/KineLVideoPlayer#21]
(日本語が下手だったらごめんなさい。インターネットの翻訳機を使っています。)

何らかのオーディオファイルを再生している場合、[Speaker Right]ゲームオブジェクトからは音声が再生されません。
1.1.2でのみ発生する問題

新鮮なテストワールドからのオーディオを、ビデオプレーヤー、UdonSharp、SDK3を使ってワールドのみでテストしてみました。

これは、私がテストした曲です。右チャンネルのボリュームと楽器はインゲームでは再生されません。
https://youtu.be/0qsi_CVzynM

ビデオプレーヤーのゲームプレイ動画が動作しない。
https://youtu.be/y6rVe0xWIv4

**Comment by niwaniwa** [comment]
AudioSourceを一つに減らしたうえで適切な設定を行い、音が正常に聞こえるようにしました。

ご報告大変ありがとうございました。今後ともよろしくお願いいたします。
